/*
 * To change this license header, choose License Headers in Project Properties. To change this
 * template file, choose Tools | Templates and open the template in the editor.
 */
package co.com.ies.pruebas.simulacion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import co.com.ies.pruebas.simulacion.SorteosHelper.Sorteo;

/**
 *
 * @author desarrollo
 */
public class NewJFrame extends javax.swing.JFrame {

  Sorteo sorteoSeleccionado;

  ResultadoSimulacion resultadoSimulacion;

  private JRadioButton rdbtnBingo;

  private JRadioButton rdbtnKeno;

  /**
   * Creates new form NewJFrame
   */
  public NewJFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Simulador Bingo");

    jButton1.setText("Buscar Ganadores");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    /*jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {{null, null}, {null, null}, {null, null}, {null, null}},
        new String[] {"Figura", "Ganadores"}) {
      Class[] types = new Class[] {java.lang.Long.class, java.lang.Long.class};
      boolean[] canEdit = new boolean[] {false, false};

      public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit[columnIndex];
      }
    });*/
    jScrollPane1.setViewportView(jTable1);

    jLabel1.setText("Presione para iniciar la simulacion");

    JComboBox<String> comboBox = new JComboBox<>();

    JLabel lblNewLabel = new JLabel("Seleccione el sorteo");

    JButton btnNewButton = new JButton("Cargar Sorteos");
    btnNewButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent arg0) {

        comboBox.removeAllItems();

        SorteosHelper sorteosHelper = new SorteosHelper();
        List<Sorteo> sorteos = sorteosHelper.getSorteos();

        // List<String> strings = new ArrayList<>(sorteos.size());
        for (Sorteo sort : sorteos) {
          String sorteo = "Id:" + sort.getId() + ", Fecha:" + sort.getFecha() + ",Figuras:"
              + sort.getFiguras().toString();
          comboBox.addItem(sorteo);
          // strings.add(Objects.toString(object, null));
        }
        // Accion a realizar cuando el JComboBox cambia de item seleccionado.
        comboBox.addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {
            int selectedIndex = comboBox.getSelectedIndex();
            System.out.println("selectedIndex = " + selectedIndex);
            Sorteo sorteo = sorteos.get(selectedIndex);
            System.out.println("sorteo = " + sorteo);
            sorteoSeleccionado = sorteo;
            lblNewLabel.setText(comboBox.getSelectedItem().toString());
          }
        });
      }
    });

    JButton btnGuardarBalotas = new JButton("Guardar balotas");
    btnGuardarBalotas.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent arg0) {

        SorteosHelper helper = new SorteosHelper();
        helper.saveBalotasSorteo(sorteoSeleccionado.getId(), resultadoSimulacion.getBalotas());


      }
    });

    JLabel lblGuardarBalotas = new JLabel("5. Guardar Balotas");

    JLabel lblBusqueGanadores = new JLabel("4. Busque Ganadores");

    JLabel lblSeleccioneEl = new JLabel("2. Seleccione el sorteo");

    JLabel lblCargarSorteos = new JLabel("1. Cargar Sorteos ");

    JLabel lblSeleccioneEl_1 = new JLabel("3. Seleccione el tipo de sorteo");
    lblSeleccioneEl_1.setHorizontalAlignment(SwingConstants.CENTER);

    rdbtnBingo = new JRadioButton("Bingo 75");
    rdbtnBingo.setSelected(true);

    rdbtnKeno = new JRadioButton("Keno");

    grupo1 = new ButtonGroup();

    grupo1.add(rdbtnKeno);
    grupo1.add(rdbtnBingo);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    layout.setHorizontalGroup(
      layout.createParallelGroup(Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(43)
          .addGroup(layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jScrollPane1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(Alignment.LEADING)
                .addComponent(lblBusqueGanadores)
                .addComponent(lblGuardarBalotas, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                  .addComponent(lblSeleccioneEl_1, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                  .addComponent(lblSeleccioneEl, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(lblCargarSorteos, Alignment.LEADING)))
              .addPreferredGap(ComponentPlacement.UNRELATED)
              .addGroup(layout.createParallelGroup(Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(rdbtnBingo)
                  .addGap(10)
                  .addComponent(rdbtnKeno))
                .addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 331, GroupLayout.PREFERRED_SIZE)
                .addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(btnGuardarBalotas, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                  .addGap(18)
                  .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 457, GroupLayout.PREFERRED_SIZE)
                  .addGap(24))
                .addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE))))
          .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(Alignment.TRAILING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addGroup(layout.createParallelGroup(Alignment.BASELINE)
            .addComponent(btnNewButton)
            .addComponent(lblCargarSorteos))
          .addPreferredGap(ComponentPlacement.UNRELATED)
          .addGroup(layout.createParallelGroup(Alignment.BASELINE)
            .addComponent(lblSeleccioneEl)
            .addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(ComponentPlacement.RELATED)
          .addComponent(lblNewLabel)
          .addGap(9)
          .addGroup(layout.createParallelGroup(Alignment.BASELINE)
            .addComponent(lblSeleccioneEl_1, GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
            .addComponent(rdbtnBingo)
            .addComponent(rdbtnKeno))
          .addPreferredGap(ComponentPlacement.RELATED)
          .addGroup(layout.createParallelGroup(Alignment.BASELINE)
            .addComponent(lblBusqueGanadores)
            .addComponent(jButton1)
            .addComponent(jLabel1))
          .addGap(26)
          .addGroup(layout.createParallelGroup(Alignment.BASELINE)
            .addComponent(lblGuardarBalotas)
            .addComponent(btnGuardarBalotas))
          .addGap(18)
          .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
          .addGap(22))
    );
    getContentPane().setLayout(layout);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
    final long tic = System.currentTimeMillis();
    Sorteo sorteo = sorteoSeleccionado;
    
    ResultadoSimulacion ganadores = null;
    jLabel1.setText("Calculando..");
    if(rdbtnBingo.isSelected()) {
      
      SimulacionBingo simulacion = new SimulacionBingoImpl();
      
      List<Integer> figuras = new ArrayList<>();
      
      Map<Integer, String> figurasSorteo = sorteo.getFiguras();
      for (Entry<Integer, String> integer : figurasSorteo.entrySet()) {
        figuras.add(integer.getKey());
      }
       
      resultadoSimulacion = simulacion.consulta(figuras);
      jTable1.setModel(toTableModel(resultadoSimulacion.getGanadores()));
      
    }else {
      
      //TODO llamar el objeto de simulacion
      
      
    }
    
    final long tac = System.currentTimeMillis();
    final long tictac = tac - tic;
    System.out.println("------ tiempo" + tictac);
    
    if(resultadoSimulacion == null) {
      return;
    }
    
    int cantidadBalotas = (ganadores != null)? resultadoSimulacion.getCantidadBalotas():0;
    jLabel1.setText("Tiempo transcurido:" + tictac + " ms, Cantidad de Balotas: "
        + cantidadBalotas);
    System.out.println("------ " + ganadores);
    
    
    
  }// GEN-LAST:event_jButton1ActionPerformed

  public static TableModel toTableModel(Map<?, ?> map) {
    DefaultTableModel model = new DefaultTableModel(new Object[] {"Figura", "Cantidad"}, 0);
    map.entrySet().forEach((entry) -> {
      model.addRow(new Object[] {entry.getKey(), entry.getValue()});
    });
    return model;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
          .getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new NewJFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private ButtonGroup grupo1;
}
